# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "docker" do |d|
  end

  config.vm.provision :shell do |s|
    s.privileged = false
    s.env = {LC_ALL:ENV['LC_ALL']}
    s.path = 'vmbin/provision.sh'
  end
end
